### ISSUE TITLE
game keeps crashing every few seconds

### ISSUE THREAD

**Issue by nikolaskaipel** [ensoulsharp-io/EnsoulSharp.Dependencies#45]
Game just crashes every few seconds :(

**Comment by nikolaskaipel** [comment]
legacy mode activated. whenever i get into game, instantly exits and the reconnect screen pops up

**Comment by iMixSwag** [comment]
Same to you? I tought i have  something to install on my PC to make the software to work, but now i think its from them, lets just wait!

**Comment by krisoft20** [comment]
https://www.mediafire.com/file/8n66za9u05o24d1/hotfix12.3_garena.rar/file

use hotfix, it means download that file from above, then login to the league client (be in main menu) and drag drop those 2 files to League of Legends/Game folder (you need to do it every time you login to the game because gave patch those files).

**Comment by alowmo** [comment]
> https://www.mediafire.com/file/8n66za9u05o24d1/hotfix12.3_garena.rar/file
> 
> use hotfix, it means download that file from above, then login to the league client (be in main menu) and drag drop those 2 files to League of Legends/Game folder (you need to do it every time you login to the game because gave patch those files).

NOT WORKING
